config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  get '/parties/new', to: 'parties#new', as: 'new_party'
  get '/parties/join', to: 'parties#join', as: 'join_party'
  get '/parties/left', to: 'parties#left', as: 'left_party'
  patch '/delete', to: 'parties#delete', as: 'delete'
  devise_for :users
  resources :users
  devise_for :parties
  resources :parties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
	belongs_to :owner 
end

app/models/owner.rb
class Owner < ApplicationRecord
	has_many :dogs
	has_many :partys
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/party.rb
class Party < ApplicationRecord
	has_many :users
	devise :rememberable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :party
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	


end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_filter :authenticate_trainer!

  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def leave
	   @owner.party
  end

  def join
	 @owner.party=  current_party 
  end


end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
	def create 
		@party = Party.new(param)
    if @party.save
      redirect_to parties_path
    else 
      flash[:error] = @party.errors.full_messages.to_sentence
      redirect_to parties_path
    end
	end


  def index
    @parties = Party.all
  end

  def show
    @party = Party.find(params[:id])
  end

  def param
	 params.require(:party).permit(:name)
   end 

  def delete
    @party = Party.find(params[:id])
    @party.destroy
    redirect_to parties_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dog/dog.html.erb
<h3>Dog</h3>
<p>Dog Breed: <%= dog.breed%> </p>
<p>Dog Weight: <%= dog.weight%> </p>

app/views/home/index.html.erb
<h3>Welcome to PuppyParty</h3>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Party Time', parties_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/owner/show.html.erb
<h3>Owner</h3>
<p>Name: <%= @owner.name if @owner.name %></p>
<p>Park: <%= @owner.park if @ owner.park %></p>
<p>Dogs:</p>
<% @owners.dogs.each do |dog| %>
<li><%= dog.name %> Weight: <%= dog.weight %> Breed: <%=dog.breed %></li> 
<% end %>

app/views/pages/about.html.erb
<% content_for :title do %>About DogParty<% end %>
<h3>About DogParty</h3>
<p>
DogParty was created in 2016 by three UC Berkeley students: Enrique Lopez, Gabrielle Balanon, and Daniel Ho
in their Ruby on Rails DeCal.
</p>
<h3>Why?</h3>
Why not? We have daily planners, wedding planners, workout planners, and even
planners to remind us when to drink water... but no apparatus to help us plan
fun dates for our favorite buddies? Ludacrous. We're here to fix that.

<h3>How to Use DogParty</h3>
Here'a an easy step-by-step tutorial to help you out.
<p>
  1. Create an account using the Sign Up button on the homepage.
  <br>
  2. Sign in.
  <br>
  3. Choose a party that fits into your schedule. If you don't see one
  you may create your own party using the CREATE button.
  <br>
  4. VOILA. You're about to get your party on.
</p>
<h3>Enjoy!</h3>
<img src="http://www.dogbreedscentral.com/wp-content/uploads/2014/10/small-dog-breeds-central-banner-01.jpg">

app/views/parties/_party.html.erb
<%= party.name %>

app/views/parties/index.html.erb
    <h3>Parties 🎉 </h3>
    <p>Below you will find a ton of parties you can join. If none of the times or places work for you,
      no worries!
      <br>
      Go ahead and create your own party using the "Create a Party" button located
      at the bottom of the screen.</p>
      <%= button_to "Create New Party", new_party_path, :method => :get %>


<div class="container">
 <div class="row">
    <div class="column">
      <table class="table">
        <tbody>
            <% @parties.each do |party| %>
            <tr>
              <li><%= party.name %></li> 
              <%= button_to "Join Party", join_party_path, :method => :get %>
              <%= button_to "Leave Party", left_party_path, :method => :get %>
              <%= button_to "Delete", delete_path(id: party), :method => :patch %>  
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/parties/join.html.erb
<h3>Best decision of your (dogs) life! </h3>

<img src="http://hollywoodpetparties.com/wp-content/uploads/2013/11/Events-party.jpg">

app/views/parties/left.html.erb
<h3>You Just Left the Party.</h3>
<h3>Your dogs loss :( </h3>
<img src="http://www.themonolith.com/wp-content/uploads/Sad-Dog.jpg">

app/views/parties/new.html.erb
<h2> Give us the day and time of your party! </h2>
<%= simple_form_for Party.new do |f| %>
  Name <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/parties/show.html.erb
<h3>Party</h3>
<p>Name: <%= @party.name if @party.name %></p>
<p>Owners Attending:</p>
<% @party.users.each do |owner| %>
<%= button_to "Join!", join_path(id: user), :class => "button medium", :method => :patch %>  
<%= button_to "Leave!", leave_path(id: user), :class => "button medium", :method => :patch %> 
<% end %>

app/views/partys/_party.html.erb
<td><%= link_to party.name, owner %></td>

app/views/partys/index.html.erb
    <h3>Parties 🎉 </h3>
    <p>Below you will find a ton of parties you can join. If none of the times or places work for you,
      no worries!
      <br>
      Go ahead and create your own party using the "Create a Party" button located
      at the bottom of the screen.</p>
    <div class="column">
      <table class="table">
      <%= button_to "Create New Party", new_party_path, :method => :get %>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/partys/show.html.erb
<h3>Party</h3>
<p>Name: <%= @party.name if @party.name %></p>
<p>Owners Attending:</p>
<% @party.owners.each do |owner| %>
<li><%= owner.name %> Dogs: <%= owner.dogs %> </li>
<%= button_to "Join!", join_path(id: owner), :class => "button medium", :method => :patch %>
<%= button_to "Leave!", leave_path(id: owner), :class => "button medium", :method => :patch %>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>It's a DogParty!</h1>
            <p class="lead">Welcome to DogParty. Please login to get the party started.</p>
            <img src="http://cdnblog.rentcafe.com/blog/wp-content/uploads/2012/05/Fotolia_34937840_Subscription_L.jpg">
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->